---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  quote: '"' # double quote var to support substitution as quote
  TIMEZONE: "Europe/Amsterdam"
  # Cluster Internal IP's
  CLUSTER_INTERNAL_ROUTE_IP: 10.20.50.103
  CLUSTER_EXTERNAL_ROUTE_IP: 10.20.50.104
  CLUSTER_K8S_GATEWAY_IP: 10.20.50.101
  CLUSTER_MQTT_IP: 10.20.50.105
  CLUSTER_HOME_ASSISTANT_IP: 10.20.50.106
  CLUSTER_PLEX_IP: 10.20.50.107
  CLUSTER_DNS_IP: 10.20.50.108
  CLUSTER_PIOLE_IP: 10.20.50.120
  # External Services
  LAN_UNIFI_GATEWAY_IP: 10.20.0.1
  LAN_ZIGBEE_ADAPTER_IP: 10.20.30.10
  LAN_ZIGBEE_ADAPTER_PORT: "6638"
  # Redis DB id's
  REDIS_IMMICH_REDIS_DB: "1"
  REDIS_OUTLINE_REDIS_DB: "3"
  # Service URLs
#  POSTGRES_HOST: "production-rw.database.svc.cluster.local"
#  POSTGRES_PORT: "5432"

