---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  quote: '"' # double quote var to support substitution as quote
  TIMEZONE: "Europe/Amsterdam"
  # Cluster Internal IP's
  CLUSTER_INTERNAL_ROUTE_IP: 10.20.50.103
  CLUSTER_EXTERNAL_ROUTE_IP: 10.20.50.104
  CLUSTER_K8S_GATEWAY_IP: 10.20.50.101
  CLUSTER_MQTT_IP: 10.20.50.105
  CLUSTER_HOME_ASSISTANT_IP: 10.20.50.106
  CLUSTER_PLEX_IP: 10.20.50.107
  CLUSTER_DNS_IP: 10.20.50.108
  CLUSTER_TDARR_IP: 10.20.50.109
  CLUSTER_GAMES_IP: 10.20.50.110
  CLUSTER_PIOLE_IP: 10.20.50.120
  # External Services
  LAN_UNIFI_GATEWAY_IP: 10.20.0.1
  LAN_ZIGBEE_ADAPTER_IP: 10.20.30.10
  LAN_ZIGBEE_ADAPTER_PORT: "6638"
  LAN_TRUENAS_IP: 10.20.20.10
  TRUENAS_MEBIALIBRARY_PATH: "/mnt/main/medialibrary"
  TRUENAS_IMMICH_PATH: "/mnt/fast/immich"
  TRUENAS_PHOTO_COLLECTION_PATH: "/mnt/fast/photos"
  # Redis DB id's
  REDIS_IMMICH_REDIS_DB: "1"
  REDIS_OUTLINE_REDIS_DB: "3"
  # Service URLs
  POSTGRES_HOST: "production-rw.database-system.svc.cluster.local"
  POSTGRES_PORT: "5432"
  # Networking
  NETWORK_VPN_NIC: "ethSel0.60"
  NETWORK_HOMELAB_GATEWAY: "10.20.20.1"
  NETWORK_BGP_GATEWAY: "10.20.50.1"
  NETWORK_VPN_GATEWAY: "10.20.60.1"
  NETWORK_CLUSTER_POD_CIDR: "10.42.0.0/16"
  NETWORK_CLUSTER_SERVICE_CIDR: "10.43.0.0/16"

