apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  PRIMARY_SECRET_DOMAIN: ENC[AES256_GCM,data:2DKKzo7Yd9dvLmLG,iv:MMU3uzCfgFuF3CaSEWij3TcpWvXLy+NmVG9TjX058PE=,tag:5xQhR3EayYr/8+Wm8hmzyw==,type:str]
  SECONDARY_SECRET_DOMAIN: ENC[AES256_GCM,data:TIcRyC+EnA2TtnLMQQ==,iv:wbj6O5lrYUi6/OmcZ2cjxVbmrpKgBbtK1zgjKHkJNMA=,tag:wvB6JF3LUNjusnj32scCJQ==,type:str]
  TERTIARY_SECRET_DOMAIN: ENC[AES256_GCM,data:YPekjzkODiqU89xLdldWt1k=,iv:AfOF9SWDIX3bD3T4jjcOZVROVCBFUD0ysNK4PN0w1zk=,tag:cEGPWQf0XFdvhqdULPW8Tg==,type:str]
  WASABI_ACCESS_KEY_ID: ENC[AES256_GCM,data:pqy4ZJ9ZYE6AJhg51lT+VlU7eX8=,iv:wuqpx0YvhtYiO8HEqa985taxy24isxMZhBoZF4VPX/c=,tag:sNAIrJ4tqRmgkhxWs+W19w==,type:str]
  WASABI_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R5QqJ8O8KG92Dnf2NrIUGT3jTW4I2kZ2gnOs2aJmPG5Rx/TGRa6aRg==,iv:kIMjpLXRY6jHvDCw2WTfmRwA9SjRradrmuqD56WIYko=,tag:BgNNouG9DzbB66dk2juw9w==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T20:54:29Z"
  mac: ENC[AES256_GCM,data:zEBQgEA6fdwVxOjlvWjulx2MIlpmi7Y/qDof9L09EcteIOvPW4kjVYp9ZuzKTPPvEkfvrZH2C01da00BJ6e/eISRGg2cQE5jO3yZ8go0Bz1OPV7dV7v1IWVUZEXLfTXcxDWl0EKalVOQGnOtZqxLMYywv0N3GX3uZl6od508dzc=,iv:ADbCMwCmABPCyRZI4mGv2N3O/iMQv8THb+Qh6+7/qXM=,tag:06sYfjv0hZBB+gTh3E6mlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
