---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-flaresolverr
  namespace: &namespace media
spec:
  path: ./kubernetes/apps/media/flaresolverr/app
  targetNamespace: *namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
