router bgp 65000
  bgp bestpath as-path multipath-relax
  no bgp ebgp-requires-policy
  bgp router-id 10.20.20.1
  neighbor home-ops peer-group
  neighbor home-ops remote-as 65001
  neighbor 10.20.20.51 peer-group home-ops
;   neighbor 10.20.20.52 peer-group home-ops
;   neighbor 10.20.20.53 peer-group home-ops
;   neighbor 10.20.20.54 peer-group home-ops
  neighbor 10.20.20.55 peer-group home-ops
;   neighbor 10.20.20.56 peer-group home-ops
;   neighbor 10.20.20.57 peer-group home-ops

  address-family ipv4 unicast
    neighbor k8s next-hop-self
    neighbor k8s soft-reconfiguration inbound
  exit-address-family
exit
