---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 27.0.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      resourcesPreset: "small"
      persistence:
        enabled: false
    replica:
      resourcesPreset: "small"
      persistence:
        enabled: false
    architecture: replication
    sentinel:
      enabled: true
      image:
        repository: bitnami/redis-sentinel
        tag: "latest@sha256:ab4951733cbc8cd8d27257a1db4d0449df3cc0a22d58136630c4ad1ac42eea0c"
        pullPolicy: IfNotPresent
      resourcesPreset: "small"
      masterSet: redis-master
#      getMasterTimeout: 90
#      startupProbe:
#        failureThreshold: 2
      persistence:
        enabled: false
    networkPolicy:
      enabled: false
    image:
      repository: bitnami/redis
      tag: "latest@sha256:341edafd5622a1e47e4b3ab379913de84ea4a50d534f40aaa903a3825e0e1cf1"
      pullPolicy: IfNotPresent
    metrics:
      enabled: true
      image:
        repository: bitnami/redis-exporter
        tag: "latest@sha256:826966816fe3cec63edfb19d97424df415a5045189fba850862e20332ee201c1"
        pullPolicy: IfNotPresent
      resourcesPreset: "small"
      serviceMonitor:
        enabled: true
