---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 27.0.12
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      resourcesPreset: "small"
      persistence:
        enabled: false
    replica:
      resourcesPreset: "small"
      persistence:
        enabled: false
    architecture: replication
    sentinel:
      enabled: true
      image:
        repository: bitnami/redis-sentinel
        tag: "latest@sha256:99c9cddfa8729dc4828777df63d4eb201be72661d5d2128497d4dbd45a5112df"
        pullPolicy: IfNotPresent
      resourcesPreset: "small"
      masterSet: redis-master
#      getMasterTimeout: 90
#      startupProbe:
#        failureThreshold: 2
      persistence:
        enabled: false
    networkPolicy:
      enabled: false
    image:
      repository: bitnami/redis
      tag: "latest@sha256:b436e0a73c2d4cee3087f3f5ca8212c9d473411f424ae28ef968d6414a728da8"
      pullPolicy: IfNotPresent
    metrics:
      enabled: true
      image:
        repository: bitnami/redis-exporter
        tag: "latest@sha256:29641924c23cbb5e76a27017f9975f69d4949ba1cbad62a965f5e7f7a10c63fd"
        pullPolicy: IfNotPresent
      resourcesPreset: "small"
      serviceMonitor:
        enabled: true
