apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:7jFSmV7YI9mP76cEtsNDtKEthzRFOZJ11EL9B40xtJeO5KvWE1mXtg==,iv:ZnPyqR8FhzZA6T+0cIJMgL0H/hMH+qIPy98YhtWkvQY=,tag:k9HUT0oP70Jjznxy6N0I/w==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUlc5aWEyNmJrZFFxQmNM
        KzNxajBOMG0yUWNqYWgxdW9mSHNWMTdhMUFFCjZySmx1UWhGZ3UyMHZza0RhMWEx
        elVsOGhPL2NHekRXMDk4N1AySnhQRHMKLS0tIDBBU2dGSU1Camh3YzlkcVR6VUd0
        dzFZUnhCb1pubjhnTTlySmRkQWtpcm8KOYqfY87HnKnHG4XL7xGm+fljYijMCygZ
        nHmlnehIGlioh7bMDWwozQ5YSvmElZOydspw9EesDrHV4xEkSZgoKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T22:44:06Z"
  mac: ENC[AES256_GCM,data:qtFL68e0gBvrxT2r6TdA8Oh9U1qFdf+mKTZD8HR1IzYu7zdBacNavVwj4eMwi1SSSpg3RGt56fWgNQIF+e9aB214pUGUAnMxiPY7Q/sNqULAtBpFWsjP/lacSzi5w2YjOC5Pt+aTTzgDWacyX7U1PxT2toBVAm35irBXyovYihQ=,iv:qzN6PSYofEZMZCBuYlsTDF+5W2g9EL4+vKNynAxvirE=,tag:vRg9hf8Z7L9tEJOIuIXxTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
