apiVersion: v1
kind: Secret
metadata:
  name: invoice-ninja-db
stringData:
  MARIADB_DATABASE: ENC[AES256_GCM,data:LgAdvO3YVv/EsvnmLQ==,iv:rAN85cVuQsHTssmqzQtMUsjlAKcsu82j9Qorp6ixdpI=,tag:dotD/svIQzrObrVUr9HFww==,type:str]
  MARIADB_USER: ENC[AES256_GCM,data:6xwgTrOE7srsTYghow==,iv:/aZpCarjL/nslyxzdyj/AykwU5jxOquuhMGlA8mABM4=,tag:vqk7u5t2aSTKuuLifMKveg==,type:str]
  mariadb-password: ENC[AES256_GCM,data:HQtQmTdoRSgzm0L7F/eD4pxWy9/6TtmUTA==,iv:jzMZDOCzoPtAyUH/1QubJeM/9nPl+/yoJdcJMA1/4ow=,tag:ZZtOsEFTfz+2u5ipvpz1vA==,type:str]
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:4RWsKMRb5iIp8u7kplDXC30XwuKZd1ctuw==,iv:FKNovK9LBmNGejmNCkIuEUktPbQZrqMXs6V5/QWLfOQ=,tag:d8FxVS/GtULvjmGSiiKS9g==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T11:36:00Z"
  mac: ENC[AES256_GCM,data:6SHe/g9EChfzxbznK+qiOxHGzb7IS15UVrbupLai7BYSRimtsKo/lpQIsow9QVWGyVtidm29wkO7IbfE7hVIwew1TWULBENCAD8x0Kx2SSqLqJv2KahHjO25IULBcpqmJ3RhRGxE8WGwg/ZsajfFLAVKUniaEoMby34anEbsFe8=,iv:MilDWgnRmcfHGXJSVzC2kE9jIIuuq+Z05qDLuoHxBjM=,tag:HQ7Ef/44YGfSFH5hStyiMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
