apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pry1NwirTBUp8v6Woww+3kFz4izF9UOQxPJ3AfcFruZJu2hRYyWCAA==,iv:srRsad+lpxdPwNM7nr3lLqWa4QYd/PgHHslGcJYaGbg=,tag:5HgKm2M8ecBB4dB5NkZJSA==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTHIvejFWejlrQmFYRjdP
        cGxXMUJmYVlrRGFuT3FtVzdQQTl6WXYvQUdNCm9KaWwvNTV3RU1VNHNaNFM3TkEz
        WUh0K1pnNUpIcDlrVkJzUktPelNHR2sKLS0tIHdiQ1B5QW05Q2YvY1BldmFtMlRN
        WHN4QzU5NHNFQlRZVEowbTA5TExZaDgKlXW1p5P9oWEYEV4N30By47jP2ooqnKOM
        3WSjHD8mVsCZPS0GWem2bLEWIqXINnAzk76Xdu3asrdeSPKcrgSiDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T10:55:00Z"
  mac: ENC[AES256_GCM,data:Gm6BOWVAg3OwnmPqCEO17Yug6gbt8Zfa5xwEyUezAv2PaweDsr5Nx0PYiCb9oU0KdHPHKK7JB2kpfrDPcss2yV358KOdlDspbD6VOSn9mgL46XcYxS5EWY0DgJPma3K/ZMOZUgZHCPRa0niaHSJvYhDl/D5T/G+PsER7Ya6ANFU=,iv:3X/phUFUJMRfkYwimd4RnUUqpc7TVmk8HVPYinr4KIE=,tag:h6+O/rG2+R7ORbdXKn6jSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
