apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+o5tcnfL7S9CskBk,iv:+lwuSmEurgs2PJtNpositb1KKon+nyOzefM6ZhQ0pqg=,tag:oZu29iX/4bkv9LKnzM1LOQ==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T10:55:00Z"
  mac: ENC[AES256_GCM,data:91t2In9eCp0csqfxuodqHZKCrpBoSNX8KI06wlDL91RqNuciyLwAAibnr62R1WXxQ4sFfte5TayNJiA/CvKRwesUs24ZjBzrL7hxHvL8d3lxL6iX3Mw/YTF6dOWihFxg6rUKC28pVJPdaHzDrrXHysZN1tZakY8tW1GRIBkVQIg=,iv:BvNP+iCCO7HBRg7I4j1OunI38tANJwqqSVwgDM6gNFQ=,tag:/OYo/+eFs4POVYupGtk5bQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
