apiVersion: v1
kind: Secret
metadata:
  name: minecraft-rcon-external
type: Opaque
stringData:
  rcon-password: ENC[AES256_GCM,data:oNqq7jCJvf2MVHM=,iv:T9KJnllOgQqrkuwzdSTyhb/E4uZDYLLZT2cllW+jNXg=,tag:IEFW9zIrHRGbjvPhLaPIig==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUlc5aWEyNmJrZFFxQmNM
        KzNxajBOMG0yUWNqYWgxdW9mSHNWMTdhMUFFCjZySmx1UWhGZ3UyMHZza0RhMWEx
        elVsOGhPL2NHekRXMDk4N1AySnhQRHMKLS0tIDBBU2dGSU1Camh3YzlkcVR6VUd0
        dzFZUnhCb1pubjhnTTlySmRkQWtpcm8KOYqfY87HnKnHG4XL7xGm+fljYijMCygZ
        nHmlnehIGlioh7bMDWwozQ5YSvmElZOydspw9EesDrHV4xEkSZgoKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T08:21:46Z"
  mac: ENC[AES256_GCM,data:Iq4JjS3KdeP9ba6T8+AftdppJ54zN5VOdyYdX2tOXQbsvVsQ0wvArP0cmKuRSkR47IxXxXIZJ90m9rXPuYcD8sk713PI6TqxwVMYnWR21or91hqWR6oj4XFeq+rz80bvZ43IkQ4RryXECD5Sb25vVvbHtNbTVMP5csroVLeOVEw=,iv:kXV0+tkc3i6934PequwQ5reyMM4Z4QCCqIc0l1Mjt+8=,tag:TQINbcM0ts35MJEtJ0xK1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
