apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FIqi+VZvOKKPPM9FjLqGgf75o+G5PzORjIQqLLmiZLA=,iv:rlp/fGP7Sn/nclPWgLyygM0t4O+9NSkm6pMIE6ZKA/8=,tag:i+YbGhsB82uFe7vMaOWx5g==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SlVLenBsL1ppaVF6Mjgz
        bk1nT0lZM09GUG1rOFNYSFMxcTJGQ05scEJFCmVORkxTekkyODFjOWJjSHc0ckJQ
        akJnbGJmeHBmM2NlQy9sK3Z2bUlTV2cKLS0tIDh2Zi85VlJCNEk3eHJNN1d3aVZ3
        SU4zYVF4OGtobGJsZXc5WTQ3YXdjNDQKxjhSAbOxUA59d3PxPlmVZrOXdZt01GH+
        ajgVqPkrsQIsABerxbe7NLo17f/5uI6CmAerhdSOsGdRUWehkcVW2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T10:55:00Z"
  mac: ENC[AES256_GCM,data:4XtRo3F68vl6uuncYW552hzLXQH1ON5LXZ/BX3t8Goo5ly60THUObG15geed2B8hQpHq5uPGu6zdv4FRSZFQsjy+9eNViG+km+k+5gprpTeBi9l8wxSMVukU8WPEzFBzRdNTrp28I9xl7BtTFL3kr1CX6EhD1OklY+Jpbo7T+Pg=,iv:V2mbwRDjLRDK7o24pYQ+aXTPeil3BU/EEPhgjo1VFLA=,tag:CvokSRJBXPjgxb/LBLyrWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
