---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      qbittorrent:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4@sha256:bb82ad6668f8eda1d0fcce6c1341498bfa879155bb1295cd9d314a2c35c07a01
              pullPolicy: IfNotPresent
            env:
              QBT_WEBUI_PORT: &port 8080
              TZ: "${TIMEZONE}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
          gluetun:
            enabled: true
            image:
              repository: qmcgaw/gluetun
              tag: v3.41.1
            probes:
              startup:
                enabled: false
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - "wget -nv -t1 -O - 'http://127.0.0.1:9999' || exit 1"
                  initialDelaySeconds: 30
                  timeoutSeconds: 2
                  failureThreshold: 3
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
            resources:
              requests:
                memory: 128Mi
              limits:
                memory: 256Mi
            envFrom: &secret
              - secretRef:
                  name: vpn-authentication
            env:
              DOT: "off"
              FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/16,10.43.0.0/16,10.20.20.0/24,10.20.50.0/24"
              HTTPPROXY: "on"
              IPV6_DISABLED: "true"
              PORT_FORWARD_ONLY: "on"
              VPN_TYPE: wireguard
              LOG_LEVEL: "info"
              VPN_INTERFACE: &interface wg0
          port-forward:
            enabled: true
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.3"
            resources:
              requests:
                memory: 1Gi
              limits:
                memory: 6Gi
            env:
              PORT_FORWARDED: "/tmp/gluetun/forwarded_port"
              HTTP_S: "http"
              QBITTORRENT_SERVER: localhost
              QBITTORRENT_PORT: *port
            envFrom:
              - secretRef:
                  name: qbit-authentication
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
      proxy:
        controller: qbittorrent
        ports:
          http-proxy:
            port: 8888
            protocol: TCP
          shadowsocks:
            port: 8388
            protocol: TCP

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${PRIMARY_SECRET_DOMAIN}"
          - "qbit.${PRIMARY_SECRET_DOMAIN}"
          - "{{ .Release.Name }}.${SECONDARY_SECRET_DOMAIN}"
          - "qbit.${SECONDARY_SECRET_DOMAIN}"
        parentRefs:
          - name: internal-gateway
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: qbittorrent
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      medialibrary:
        enabled: true
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: "${TRUENAS_MEBIALIBRARY_PATH}"
        advancedMounts:
          qbittorrent:
            app:
              - path: /medialibrary
      tmp:
        type: emptyDir
      gluetun-data:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
