apiVersion: v1
kind: Secret
metadata:
  name: sonarr-cnpg-credentials
type: Opaque
stringData:
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:5G4I/dpq,iv:nWTQIRuc9UpGbXpRV1WFjp4+mX7ma/GSbeQs5jT0dWQ=,tag:4uVUB8iZ0SonSzYixj+BuQ==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:7dawf9fDES14IBYZ6albO2fb8Xw=,iv:prYDQoyYRNUab/Li0BRo0Bdyw1FwpCVFpD2qMx+yZIw=,tag:vSxDegDopYXZJeOuv3Rfcw==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:9/W3NVbz,iv:2lm0v0/AvDiBHIhF5XrvUwpSpBkHsV6E1QmDiM0DwUM=,tag:HI5UAYLRC0NPfOayaJ4+Pg==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T10:22:40Z"
  mac: ENC[AES256_GCM,data:CuKqp3zJWAFaPnV/L23dSp/bfaQpUpYkAUQNdw+yth4mKn5+gcJulpOQNmHr6N+sJT1ulSGFRc9pEDoqOVyEarjDSDAuryQT/1WH/OWhxDr5zIw4WfAyyK3ao4TFYwptbODpQ+LA+JZP/3EPRS3y3ckr0LJ9d0lWvPRLV9sheYw=,iv:aUWZDXh6FekWuIJUWqTjhYEOYIrsLvCLi3eicvBZ5MQ=,tag:dPzKZVLl0zzVE/kjiJ8/gw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
