---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoice-ninja
spec:
  interval: 1m
  chart:
    spec:
      chart: invoiceninja
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: invoice-ninja
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  values:
    debug: false
    image:
      registry: docker.io
      repository: invoiceninja/invoiceninja
      tag: 5.13.21@sha256:3cdf57666fdc0fc1ef089523e7e1558989b570946a6e77dd2198160c5e585955
    existingSecret: &ninja-secret invoice-ninja
    updateStrategy:
      type: Recreate
    nodeSelector:
      kubernetes.io/arch: amd64
    mariadb:
      enabled: false
    externalDatabase:
      host: "invoice-ninja-db.infinigon"
      user: invoice-ninja
      database: invoice-ninja
      port: 3306
      existingSecret: invoice-ninja-db
    pdfGenerator: "phantom"
    redis:
      enabled: false
    externalRedis:
      host: "redis-headless.database-system.svc.cluster.local"
      port: 26379
      sentinel: true
      database:
        default: "0"
        cache: "1"
    extraEnvVars:
      - name: REDIS_SENTINEL_SERVICE
        value: "redis-master"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi
    http:
      image:
        repository: bitnamilegacy/nginx
        tag: 1.29.1-debian-12-r0
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 4Gi
    persistence:
      public:
        existingClaim: invoice-ninja-public
      storage:
        existingClaim: invoice-ninja-storage
        enabled: true
