apiVersion: v1
kind: Secret
metadata:
  name: invoice-ninja
stringData:
  APP_KEY: ENC[AES256_GCM,data:jmi9POPwlPusqB4ZYv1wIhCvl0Jb+kDKOoouzvHhS2APFyG7Q8uICWIK0b7EJrJo5sef,iv:DI6Awcbs/cCSzvGtNk+74ideMWVfeOYYiuh9zmAY2Bs=,tag:JRh8t3oRlXlxn916CePMBw==,type:str]
  CACHE_DRIVER: ENC[AES256_GCM,data:MZFmCA4=,iv:8jThUfxFVhhRwNLWcXR/bJuAI7iVCBST65GVl63HoWI=,tag:h4KFlEVwfopz5uub3iBf3w==,type:str]
  QUEUE_CONNECTION: ENC[AES256_GCM,data:fINJczs=,iv:ewafD1xnxtKndPUz2KC2zeN/Ar7w7Za1KLh96Dsof0E=,tag:B+SzYWCJc/L1tC4ARk12rg==,type:str]
  SESSION_DRIVER: ENC[AES256_GCM,data:B3lxne0=,iv:3u0H0p61oJxvUKXVQY60BuPsGURUFh8MfkrcGhjaan8=,tag:dhBSoo3wup6EQtz8qizUig==,type:str]
  IS_DOCKER: ENC[AES256_GCM,data:iBRthg==,iv:3f7OTEMLYSNVSHEdmm2SzFe7sq6JFs+2xBLpeq2NnaA=,tag:uh1XlnSXKkbqPqECXPHWBQ==,type:str]
  APP_URL: ENC[AES256_GCM,data:ffvvxqMl13ugVev1mqr9GLVDZG+oCRwB8arl8Zg=,iv:uuI/W2EUEmvV3qIYoxWVe8KlKHyDaYGSJHeI6mhAJEc=,tag:1E1LfjTq/UHCxsb0j4HnZQ==,type:str]
  REQUIRE_HTTPS: ENC[AES256_GCM,data:M/hmOw==,iv:2S5OVOg8kstTLFQ+SMj1tg4BT0s90bUb0DAuPk0jXN4=,tag:LgpQ7aNbOupYSJKHLo424w==,type:str]
  WEBCRON_SECRET: ENC[AES256_GCM,data:Bjl55qjMMVcqFFLszj5cJMD52aI=,iv:jMeBrHvs1iuccixGInR8f+UOliWYh2K8LfU2zQdQaZM=,tag:kUC7KjIwuk2vwwHggjhDUg==,type:str]
  UPDATE_SECRET: ENC[AES256_GCM,data:znV7SwH6izIaA6bhM0BvIqYaZu8=,iv:UERRvEVcThwekxubPaLEuULtwmXjvAJDM1RXhVgpdho=,tag:IbARzWxhFvFP2IbbRQFtvw==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T12:08:10Z"
  mac: ENC[AES256_GCM,data:pRbCNpPq/vQXUgSW5JKPv2iezF1j9Qzd/wkCdtDugs3l+Q2phhsZhZ6VCQW6gMwc8XMhrcl6jOybLOFKWpqrptqRmMbtjMRAl8OV/iqEiIZrDyjeqyHv82GX/gKc+HTAPLkjzDPjjgHiritnw340kSrt4B+7VSKwiIsvcagw15E=,iv:F5TIoMBRT1e0bKk5zvugpvtBrzF6VgXtenKD7lvUPg8=,tag:9CYc5NmqONwrpyu12SIWiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
