---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infinigon
resources:
  - ./helm-repository.yaml
  - ./invoice-ninja-secret.sops.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
