apiVersion: v1
kind: Secret
metadata:
  name: cnpg-superuser
stringData:
  username: ENC[AES256_GCM,data:z2zAJKwmCAs=,iv:cnJqxgYf6rWhweLN/iN8RwnB7uWlqN89eky7Co5U730=,tag:CRXqG/IN9/JlC+MhqPFG7Q==,type:str]
  password: ENC[AES256_GCM,data:t7qHjGc8JLZdWghDfvObHmUh3X1tGbMbthF0RF0l4S8=,iv:xRbbQ22ggCWlu7WkW9/aeLxwUEb61CTQP7iBjvOOON0=,tag:Um7RGJcW/jNHDXBEO4u4yg==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVk2aEp3SXQ5cXdqb3gy
        VkU1M1Z4ZW9tTUpVejB3Q1pGRVd0Wnc4NVJBCnV1enp6WkNoc0RKWnhMdWFkV0E0
        Uk9BczlHZTA2ZGdNTzh3aHhnQ1haekEKLS0tIHJ0ZVVFWlRMNGgyY3U5OFBSWUpV
        VGplNmRqdWlrUWdleEZoK0Z5N28za28KTr0RPTfKZF+TK+b65ipr2yxsrTahJjVt
        dSO+xVV34XCd9RiWMhXgENpSXO5p7lw7+3CwkrxTMrkXY1NZQdwx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T09:07:43Z"
  mac: ENC[AES256_GCM,data:GPuT7O9zWxFXWobQjA8YELnYYCKsrD1pmBURUmD36HGzJ+0F4o+7L/sTdPffAk4rdSHWnr1FpZI39MC0m0HuDSCgW603wFO7XjVvB8CG/EAzr3tTo4Zu2kjQ7zpvZOpb3up8uzT+WNdc64C8hkabVSEq0cjK5KQCZsXfQpIOrwQ=,iv:186vEYugP2eaZWCWoOlOkgwOwecrvRqBE20NSCww324=,tag:Lz5RzZNU+5Es/er/c5J6zQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
