apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-cnpg-credentials
type: Opaque
stringData:
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:e8zpeUBSmgg=,iv:jQB+x21qU66avJ0iiShjBdg5KOkoIUUfohrkXAlmLHQ=,tag:QLG7Zvxyt7VLi6fzDT5X4g==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:dJfSGdUwcINiHsclq6feoaGTlSk=,iv:VfECmoCcafBamuvA3LKt/Zu1NVBRkQkMXpTr33+Mw6w=,tag:1WQqGliriDlfCpyRRsYOAQ==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:kE2LZaCWbJM=,iv:FJSOz4dd7nq6atN2zthjQcqbpM5pHs+1pt9EH2qkzAA=,tag:EwYM7Aa/hMWgmlohBroGhQ==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T11:05:26Z"
  mac: ENC[AES256_GCM,data:iaxMGqcgJ1tZ4nSoLCzBHgLsga3V7MLS1FFPQ+jMdMrpid8OfIzFhiZi5uYnZFxMr2KKlHRpN5m8bMuLQ73xVS/EadxGm47OMzOC6qmMex1LUnuAGnH2lhwCoWCO0BpQ4GxfDDuxJtSUe8BdHa1W3N+dOc7uUf2rZ3+MhyWx/5k=,iv:QseefvAYipq1j0LRTI/EOa/YwdP4J97sLVE3V0CgBII=,tag:CaS8mIIQYIaYCA/gQs+NlA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
