apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:T8vwfyy8DKwEWrImj4n98e6MIxRQJcl3aY7Sv429zkWBafcDxEdIDc8NClNYlbVDjZxdvEh+ZfA87L6pzQT+35QJ3J5JO7zWrzakuFqLd7/3yCEFYAVDgtOqSgJcOdfuxRdvsfsemtNX/Y5ZgjIkzswwdL1oRefYjuwf21RNYTOFHGQBv8xIO6sBcT+5PkotyZZGkV3X7LMfucDVKaiAwiudLGSywOms5HQe0ZFYZ0UZHc3I,iv:ZXQVQCdThczn/xZej1oyoZGH7HhxH+97LcgZHtSRjfo=,tag:nNW//4V1yg2UTZxMYfl3Kw==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL1dJaEtIM0pzWUZYTUZO
        Q3l3aXZ6allQYlkxSWh2OEhqZ1dreDIydkFFCnZ4L2hYUHJraTVTWXlrMEhUNzI0
        c1R4UVdVQ1FWd2ZhbzlxQXFBbjFCdkEKLS0tIFp4M0NkRXlGbE5lNXM3S3B4WDli
        WUU3b2ROU2NEYndWNlZWQ2JaaDRpM0UKYLqBeyc4aGhpJolSHoLmMAtOwaG0CnMC
        PeEsgqLbGNwmTod/7ppSD/hsMNtvvZuIJdkYYo8O+GgYYFOy28wGtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T10:55:00Z"
  mac: ENC[AES256_GCM,data:ZR0QqyXwsB7HHRxRc5RnfnXQ/EL8sG1exY4r1yiBp4NunNHaR5TmX1I0JNBGla54juAO7X1Lq1R0bQeuVABDeyq1v609IE7fqMhMu/28Lm7ce5gMvDE7boLzumg11sbLmxOtDBlOE6gbeBGPT5MJGCnJYKty1htbsqmvTf7HIjk=,iv:RP//F6NAY0EK2nxFtCAhU6Xu5HSxG64/vYzYp3eWJw0=,tag:9ZlXzcpZ3Iz6D791LCQbtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
