apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pod-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 7.1.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gatewa/values.yaml
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/angelnu/pod-gateway
              tag: v1.13.0@sha256:a5b032e15f7570493977b330a5a86dcffebb807d35685ad803e47afb62d105f2
          gluetun:
            enabled: true
            image:
              repository: qmcgaw/gluetun
              tag: v3.41.1
            probes:
              startup:
                enabled: false
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - "wget -nv -t1 -O - 'http://127.0.0.1:9999' || exit 1"
                  initialDelaySeconds: 30
                  timeoutSeconds: 2
                  failureThreshold: 3
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              requests:
                memory: 128Mi
              limits:
                memory: 256Mi
            envFrom:
              - secretRef:
                  name: vpn-authentication
            env:
              TZ: "${TIMEZONE}"
              DOT: "off"
              FIREWALL_INPUT_PORTS: "8080,8388,8888,9999"
              FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/16,10.43.0.0/16,10.20.20.0/24"
              HTTPPROXY: "on"
              IPV6_DISABLED: "true"
              PORT_FORWARD_ONLY: "on"
              SERVER_COUNTRIES: "Netherlands"
              SHADOWSOCKS: "on"
              VPN_PORT_FORWARDING: "on"
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_TYPE: wireguard
              LOG_LEVEL: "debug"
      webhook:
        containers:
          main:
            image:
              repository: ghcr.io/angelnu/gateway-admision-controller
              tag: dev@sha256:e9797e7d9fa2be9e246c6d2f0fbef688ea1c14e29e2e84b2c66c6806cf51d1aa
        pod:
          annotations:
            configmap.reloader.stakater.com/reload: vpn-gateway-pod-gateway
            secret.reloader.stakater.com/reload: vpn-gateway-pod-gateway
#    persistence:
#      tunnel:
#        enabled: true
#        type: hostPath
#        hostPath: /dev/net/tun
#        advancedMounts:
#          main:
#            gluetun:
#              - path: /dev/net/tun

    webhook:
      gatewayDefault: true
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"

    routed_namespaces:
      - vpn-routed

    settings:
      # -- If using a VPN, interface name created by it
      VPN_INTERFACE: wg0
      # -- Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: true
      # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: 51820
      # -- Traffic to these IPs will be send through the K8S gateway
      VPN_LOCAL_CIDRS: "10.20.0.0/24 10.20.10.0/24 10.20.20.0/24 10.42.0.0/16 10.43.0.0/16 172.16.0.0/12"
      DNS_LOCAL_CIDRS: "local ${PRIMARY_SECRET_DOMAIN} ${SECONDARY_SECRET_DOMAIN} ${TERTIARY_SECRET_DOMAIN}"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
