apiVersion: v1
kind: Secret
metadata:
  name: vpn-authentication
type: Opaque
stringData:
  #ENC[AES256_GCM,data:ywZGPr4Q7QPqpPpLiuoQUJTnyKkT,iv:eK4oY3IjH2mi9EgQZ3XtKEs8mrPxrf6qLk8tZMmCpEs=,tag:F8um3v+wVNWy49NBz42gfA==,type:comment]
  #ENC[AES256_GCM,data:GArkNuwKE5wOTe6HQo9Shm85FOkN2sXHkDikfRIYkpSrfQPaWfI=,iv:Fu5z3s7GFk8g+qDDErpmU3HAUeqXp5Inlr1e6cmxf+c=,tag:6Qe/Drkd7f1wAeDJblYoQg==,type:comment]
  #ENC[AES256_GCM,data:OYycwJvGeqn3FDsoiwyxmr6aI/aC1bQFvIpXtyEUQUiN5qkMuiGsubymp4bM0ZS7PP9Kb8CM,iv:PgwnqBVBL+83Z47C8xjNlC/ZrI+yIEPeb5C2VxIaX9s=,tag:VWxzgh8zf90egdmU2oZKOQ==,type:comment]
  #ENC[AES256_GCM,data:Pg0iVfb1qkKcljxoN2Mxd3R1um5wQhl3M95YNGVnwiyRPpc=,iv:l58qev1auUPL70aBGGzyk94H1pJkIbdMmGfp9YZX57Q=,tag:OcdjWPKMr4q2ybxFYeA29Q==,type:comment]
  #ENC[AES256_GCM,data:lerKz2AJLdCSOlqKWm3hrDCyPT40d7mfbxpEKDGdQpnsculKGnRZ65IJCxFGLS9e51EDGAtwLqr4S6JwzFHBCLjpAsVFE/ngCDIQ/ARRYytc,iv:imCaWbRnwahBK+++7qHtjVgjvI5kASvgOrjHK6WY2kM=,tag:ZC/pIxo0SwnXMaznGZOPxg==,type:comment]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:NF/VgtEEm8f9,iv:R9jIicUll2wAjPzsFq2xY/z1+EaPq0E64oULRjff3ug=,tag:wyqVXfjlmFX/cDd8mB8rtg==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:dPtdyecDF0OH,iv:Fw/xXkXTBxO64ZaitUPygyHyp96hQJ15d4ZoYMQmvQA=,tag:CVKibGw+WUQtZMADjOsvFQ==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:I83a+Dp8EXRHHaeBe6ihoyi996PjtZpl41yp0KxGQC9KhiQ6rESKYU1Rmgo=,iv:kY2WICOECt0eqQJF44V2cJrtW/ZYrFBWWSPjFZNPM2w=,tag:on2LLqFzMTSORcsjztOFiw==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:p3q43V5sBiASN7A=,iv:KFyv7Ge2iVbbD8nIxekAOGaGsdS7ugK73oxlP2Zp3gg=,tag:kAwDHVFgAZdsyw9QIY+96g==,type:str]
  LOCAL_WAN_IP: ENC[AES256_GCM,data:ZrfOy3Vs6AI8f8xeTA==,iv:NPT28VcML4OodagTf4hQ7bpUR2c3ijmfPh4JDQgTNek=,tag:ok3x7aoFY7Z/kUJU0kcf8w==,type:str]
  #ENC[AES256_GCM,data:3HbToKbMEG9VOSeXBSwpXOyG8NCkkJPD9Q==,iv:QqYNmTGVB1QA74r7qX8+XeLFY3CaFY1u2BnOW0rURRU=,tag:dwutQKdPvXQOe3F4kWeITg==,type:comment]
  VPN_INTERFACE: ENC[AES256_GCM,data:aw6u,iv:chk6PtMmPpl31PG/aktz8ZaVVY2lIqp7e48fyyw1IiA=,tag:n5CkoJKICyksOLe7aNwrBA==,type:str]
#  DNS_UPSTREAM_RESOLVER_TYPE: doh
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVk2aEp3SXQ5cXdqb3gy
        VkU1M1Z4ZW9tTUpVejB3Q1pGRVd0Wnc4NVJBCnV1enp6WkNoc0RKWnhMdWFkV0E0
        Uk9BczlHZTA2ZGdNTzh3aHhnQ1haekEKLS0tIHJ0ZVVFWlRMNGgyY3U5OFBSWUpV
        VGplNmRqdWlrUWdleEZoK0Z5N28za28KTr0RPTfKZF+TK+b65ipr2yxsrTahJjVt
        dSO+xVV34XCd9RiWMhXgENpSXO5p7lw7+3CwkrxTMrkXY1NZQdwx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T15:55:03Z"
  mac: ENC[AES256_GCM,data:4bbhE+19wAMwRrio6yfes/NScHhMt0tqCXHDK6+eBkEFoYHgyQASeZqAhltKMaceXMZ+t9MfgBvMPXT5pLzTY7OBvgGnMBI65Y8GgWSfuEWlzyr0gwERioF6gI7iC/H/3VaOePQOazIaIBU2R2k+4dQil7s3vEmzU1Tsg2gGnn8=,iv:Q2mxA6CdcW2d5mFuWnYO3ePq/R73DKW9dto9fmLyPTA=,tag:3wBCx8V78guB04ty2lu9rA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
