apiVersion: v1
kind: Secret
metadata:
  name: vpn-authentication
type: Opaque
stringData:
  PROTONVPN_TIER: ENC[AES256_GCM,data:xw==,iv:Hd3Ohwb0yXlrli7Fr30ywUQ127glA8yazjxAiwcv3bU=,tag:BFhqw0v7Yk+KdbeOOzdAAQ==,type:str]
  PROTONVPN_USERNAME: ENC[AES256_GCM,data:PRQYm+G5JRIgIKihZkWZcA==,iv:S3+wu4OO2Al71wiMiAQapm8I2ENGuzHhZhqrQrPoZg8=,tag:+N+lgX5OTD5mXk+5OLJozw==,type:str]
  PROTONVPN_PASSWORD: ENC[AES256_GCM,data:oa7X2jhnXSmQD7dnNNjGeNW7cXrbLewT1Yf0/5ewzcI=,iv:OJV1dFU9Nwd8SaAGwPNzdBo6HzpaX2q2Dlog/sRjiSc=,tag:Hqj1TYFkVWvzPMbSUVso1w==,type:str]
  PROTONVPN_SERVER: ENC[AES256_GCM,data:YPqE4hkM/MFHBaf9,iv:AZczMko1bvb/6dkNxF1VxTh9hp7Zo+8YJ3Y35X73dmE=,tag:beefVMiWXFU+rbOqnkFaOg==,type:str]
  PROTONVPN_EXCLUDE_CIDRS: ENC[AES256_GCM,data:lDu+sCAHtgC5WNmnlGPl0Fw+ThN+fROBcRpB547XS3yPEVtl0pSpLIv+EyLZDvHYtMAbOHyh,iv:4A/D6lPDqUh3uP3NDYJqoOiZAeEAfMNLdRvQUJZWEW0=,tag:5zuuJBiq0qnw8GY5c3kvjg==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:WXPJX0QrhXbeZrncYnhldLUhjuCinRC5j+oL6wH0ZBUmZSEncLCeFIleqGM=,iv:qplcNYixdDJYkJBpmcvDQEXuQ558uamB72Ah2H1+SQs=,tag:Cxbx0WbIVtfVW16zXhrVSw==,type:str]
  LOCAL_WAN_IP: ENC[AES256_GCM,data:ZrfOy3Vs6AI8f8xeTA==,iv:NPT28VcML4OodagTf4hQ7bpUR2c3ijmfPh4JDQgTNek=,tag:ok3x7aoFY7Z/kUJU0kcf8w==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:NF/VgtEEm8f9,iv:R9jIicUll2wAjPzsFq2xY/z1+EaPq0E64oULRjff3ug=,tag:wyqVXfjlmFX/cDd8mB8rtg==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:dPtdyecDF0OH,iv:Fw/xXkXTBxO64ZaitUPygyHyp96hQJ15d4ZoYMQmvQA=,tag:CVKibGw+WUQtZMADjOsvFQ==,type:str]
  VPN_INTERFACE: ENC[AES256_GCM,data:Ux+l,iv:sN62mhCW9PI7EmIMKy+jdJR0OudjIbn3L9CZyvQX0a4=,tag:I8F3OMX1bRBaUcOlNUOUjg==,type:str]
  DOT: ENC[AES256_GCM,data:42ev,iv:3PRGBZDivNmhUNqWoS1/N5tJXNXD/vWJ/Ev7Ks+Aeb8=,tag:T/oCw2k9UnL6OMjwgCEwNA==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:p3q43V5sBiASN7A=,iv:KFyv7Ge2iVbbD8nIxekAOGaGsdS7ugK73oxlP2Zp3gg=,tag:kAwDHVFgAZdsyw9QIY+96g==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVk2aEp3SXQ5cXdqb3gy
        VkU1M1Z4ZW9tTUpVejB3Q1pGRVd0Wnc4NVJBCnV1enp6WkNoc0RKWnhMdWFkV0E0
        Uk9BczlHZTA2ZGdNTzh3aHhnQ1haekEKLS0tIHJ0ZVVFWlRMNGgyY3U5OFBSWUpV
        VGplNmRqdWlrUWdleEZoK0Z5N28za28KTr0RPTfKZF+TK+b65ipr2yxsrTahJjVt
        dSO+xVV34XCd9RiWMhXgENpSXO5p7lw7+3CwkrxTMrkXY1NZQdwx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T09:54:33Z"
  mac: ENC[AES256_GCM,data:PEffigYAxp/LWzLf8at2Rgo6OapmTvJ6GkR08eu12t/q0JrQfWcgL6Xwoq656MBJvdcx5+EBWZPopeG2EqMz3XwlauuMdfXkibmSv/Ou67cH0ChaUIY+2Q33vVBF2wTXZbav5u/gVCrAoENCxr6Je8jzDgB/BYpYQFe7A+HnU5M=,iv:Yd8N3ZNcgy+vQD5IQ/kqpTPlFgcFCpmVxGUOUzSXG8U=,tag:/MMFWALcpSjjnE3TRcgnzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
