apiVersion: v1
kind: Secret
metadata:
  name: radarr-cnpg-credentials
type: Opaque
stringData:
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:KDM8HMmj,iv:2c4GDErijLifyNrAXfO/Lpnbd1942mo8AUJQExFDIP0=,tag:VBSsI4gLaixp8QEKWGSFag==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:zt7QB86/AHodOKc+D0B1v6EHnQY=,iv:JOvkkUj6BVPIRxWVM8ivzXtBOwMA6CobZGgwLGSfnSs=,tag:52Xbgj2QA5a4zPtydSmfgg==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:O61khQBl,iv:iVb4mlnOean5kn6y3u36/4YNMYZts9VGTCpk6siDmxw=,tag:3i0eWxBWrbP2ayMkSP3VVA==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T10:22:32Z"
  mac: ENC[AES256_GCM,data:nyxHqrhNcKaLeO+fxiekbDsgshgKQ6Y/ykaxwXQIKZ9AJkpCyStbl+CkHVJf6LR8HGedlk//AOYYqd3jFefCet8/Wv6EsLdtfPCTwS5O+wA/OoZvC50rDgdzVzLzjhVAEUFRrx1waYetsosoGtCh14TcFLskOdlu6oOyx2HB3gE=,iv:XWQpejyGk5fxmu/3Y0znVmRhbhtQsv2oJIkIgL7amA4=,tag:9xvzhPl02sk/RG13WssWvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
