---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      radarr:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.1.0.10293@sha256:22bbf7e924dd929b756147d8110664c3e2da37c59516b249945ab1d63657be29
              pullPolicy: IfNotPresent
            env:
              RADARR__SERVER__PORT: &port 80
              RADARR__POSTGRES__HOST: "${POSTGRES_HOST}"
              RADARR__POSTGRES__PORT: "${POSTGRES_PORT}"
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: radarr-cnpg-credentials
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: radarr
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${PRIMARY_SECRET_DOMAIN}"
        parentRefs:
          - name: internal-gateway
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: radarr
      medialibrary:
        enabled: true
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: "${TRUENAS_MEBIALIBRARY_PATH}"
