apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:gIEBXGEW3p00tdiqAH/IKai4GluYyrHNWA==,iv:blR9+pYomompXj9zVqIvoYcnYn0GTYgmdjp6OjCntV8=,tag:chVTMZo15akhggnQvTpiFw==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T20:13:11Z"
  mac: ENC[AES256_GCM,data:Zvu9vjmkyg505tlaSEv6SmwdYkd1eP+jv74kvlL6t8cHJSsTSEiLGoxiobrFnDNVpMxB2Mw/oQr9wX5aN1SvZciv4+5kX84bmg6W6YMhl5cMKiUZD7+mQH9ah/6KVqChJMVOe+vbR4VScwYnwAVCEh8toU83b9tjHUWik9u/tbI=,iv:d10qMiYb57bm8914GHTQI7cmAJW6pTERJFeN2eT+PxI=,tag:mp8Rl18XlJvvVI04RN+m7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
