apiVersion: v1
kind: Secret
metadata:
  name: minecraft-rcon
type: Opaque
stringData:
  rcon-password: ENC[AES256_GCM,data:oNqq7jCJvf2MVHM=,iv:T9KJnllOgQqrkuwzdSTyhb/E4uZDYLLZT2cllW+jNXg=,tag:IEFW9zIrHRGbjvPhLaPIig==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUlc5aWEyNmJrZFFxQmNM
        KzNxajBOMG0yUWNqYWgxdW9mSHNWMTdhMUFFCjZySmx1UWhGZ3UyMHZza0RhMWEx
        elVsOGhPL2NHekRXMDk4N1AySnhQRHMKLS0tIDBBU2dGSU1Camh3YzlkcVR6VUd0
        dzFZUnhCb1pubjhnTTlySmRkQWtpcm8KOYqfY87HnKnHG4XL7xGm+fljYijMCygZ
        nHmlnehIGlioh7bMDWwozQ5YSvmElZOydspw9EesDrHV4xEkSZgoKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T08:26:21Z"
  mac: ENC[AES256_GCM,data:T5IPc0XoNXF7Sd9bTVTYPvwmVapgS4UUKcR80NEH0vaES08DAFikKoiJwwiHf9DP7wyikAxNGBlMx2chCuto4EWnqF9m5tALfm0INVvmye7wqiX8/VADJkdE+p7mblOcGVGG93IYg5cH9Gyo4ZPDphMFljDt5w20U8ar3rwq7O4=,iv:RVeePo1y+rJSmVYBflrkIMV3El9n1akAOeS4FADQ/Vg=,tag:4zvlbTxcnj30u4+tWTqmUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
