apiVersion: v1
kind: Secret
metadata:
  name: bazarr-cnpg-credentials
type: Opaque
stringData:
  POSTGRES_USERNAME: ENC[AES256_GCM,data:476YAuTi,iv:kQ4F04wnLrBIrtaON6oRTLCsSIR6W43FDyA6HVLbQGM=,tag:77pHaVW/F25Jmxiz7/cbPw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:vr6FRrAdiZ7Q3uUbN7z4PSj+48E=,iv:4YHhajrNktNRrCD+4CQ+DHnOTfmA74JMeUH6nfEl390=,tag:ZrK9hx3Ov+uBOVnuF6pHxw==,type:str]
  POSTGRES_DATABASE: ENC[AES256_GCM,data:XREJA1C+,iv:IkWNTPM4e5M5JZxxxZxf9aIV1q4JAUjZ3WU9/2B/3M0=,tag:dvsWIo/fEXW4rtgk40WOqQ==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUFvS0JMR0ZZOVhSNWpR
        ekQ3K0tmQ1BqZDRZdHk4Z3c5Si94UDBsdUNFCjQ4Q0JqMncvcmJFbHF6MEs1YjNt
        RjBNbVF1MXZKY2orYzlBMzQ3S0ZlUDQKLS0tIHJrck9hOHRFTEdRcjJ5VVFUMmRE
        NzNJVDUvK1NEU1V3cjQ0V0NDdElnaVkKwqqhH66FAG1koZbkuX0CmfAuEfDQGfY9
        6brd8juYJ3+c4PF1TkR22tYSvK+vUBe/AHEXv9XD7vRQ/FzDLxtIEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T10:22:55Z"
  mac: ENC[AES256_GCM,data:rmtnDl5eHBz9SSbzTJq/ZtAKIqzo2EeY5+S/toqQf4v6baIOquxkikF2KOE/joHrxfm3ig/zklSFoMeMrS5hdgnINLPommop4di8AOIeNGDKYESmq7XpU9rSFQ0TO1b/6l3DMdmeG2H7m6x4SFaNBuL5smbslq5JEUZ/KJz7BqY=,iv:KAKwQyaEhDY6BkdFp3W5Bjo47sAy+mfBmY4lsOK2Rcs=,tag:s4u6Vxr8hsZ4hjvNuGsDRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
