---
web:
  port: ${GATUS_WEB_PORT}

metrics: true

storage:
  type: postgres
  path: "postgres://gatus:${GATUS_POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/gatus"

ui:
  title: Status | Bronlab
  header: Bronlab Cluster Status
  logo: https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/items/503830/ccab5ba73d4ad5291b3d11cd8e7fd7faf9b9553b.Gif
  link: https://github.com/abrondijk
  buttons:
    - name: Github
      link: https://github.com/abrondijk
    - name: Homelab
      link: https://github.com/abrondijk/home-ops

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

