apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZyP89FE7Gw2ULwj0PdxiHfwJvB4eMTYZO2f+ooU0+5xCM3GbiI/MbA==,iv:xthDQyVsVG/XtFSwcw00U+kJGizrnGJvNtnOZ9Ckqwo=,tag:sKw39KfwxBwLlDokvSQ+Cg==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVk2aEp3SXQ5cXdqb3gy
        VkU1M1Z4ZW9tTUpVejB3Q1pGRVd0Wnc4NVJBCnV1enp6WkNoc0RKWnhMdWFkV0E0
        Uk9BczlHZTA2ZGdNTzh3aHhnQ1haekEKLS0tIHJ0ZVVFWlRMNGgyY3U5OFBSWUpV
        VGplNmRqdWlrUWdleEZoK0Z5N28za28KTr0RPTfKZF+TK+b65ipr2yxsrTahJjVt
        dSO+xVV34XCd9RiWMhXgENpSXO5p7lw7+3CwkrxTMrkXY1NZQdwx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T10:55:00Z"
  mac: ENC[AES256_GCM,data:a/SlFYTZLA1KUIEyx0vnl0qemCLeyuVrRUXeNmhM/G7MspxcysZQJhJiPoejuDNx0ARXZYjNBGhECWr5JeBLB+udhjDCRz6mkKnU0tDSDFDR1ecRxSa0iAcmeCDu7ZDnfjgxCdEoYBIxnz6CXrMpGDGaOInkP9W8m4z7xRxsNHM=,iv:5ZxF35gVYdgG4jl/STwzrTuU89yyIxxFSOUPIogk3gI=,tag:MtsplKpk+j0c6ypAKm7zHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
