---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.20.20.100:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.20.20.100"
  - "cluster.brondijk.dev"
additionalMachineCertSans: *sans

clusterPodNets: [ "10.42.0.0/16" ]
clusterSvcNets: [ "10.43.0.0/16" ]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - &intelNode
    hostname: "varuna"
    ipAddress: "10.20.20.51"
    installDiskSelector:
      wwid: "naa.500a0751e298186c"
    controlPlane: true
    machineSpec:
      secureboot: false
      arch: "amd64"
      mode: "metal"
    kernelModules:
      - name: vfio_pci
      - name: uio_pci_generic
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
          - cpufreq.default_governor=performance # Default is powersave
          - iommu.passthrough=1 # Less security, faster puter
        systemExtensions: &intelExtensions
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/nfsd
            - siderolabs/nfsrahead
            - siderolabs/util-linux-tools
            - siderolabs/nvme-cli
            - siderolabs/iscsi-tools
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.transport == 'nvme'
          minSize: 2GB
          maxSize: 75GB
          grow: false
    userVolumes:
      - &ebsVolume
        name: openebs-data
        provisioning:
          diskSelector:
            match: disk.transport == 'nvme'
          minSize: 5GiB
          maxSize: 50GiB
        filesystem:
          type: xfs
    networkInterfaces:
      - &networkInterface
        deviceSelector:
          hardwareAddr: "02:26:26:02:28:3f"
        dhcp: false
        addresses:
          - "10.20.20.51/24"
        routes:
          - gateway: "10.20.20.1"
            network: 0.0.0.0/0
        vlans:
          - &vlan
            vlanId: 50
            dhcp: false
            addresses:
              - "10.20.50.51/24"
            routes:
              - gateway: "10.20.50.1"
                network: "10.20.50.0/24"
        mtu: 9000
        vip:
          ip: "10.20.20.100"
  - <<: *intelNode
    hostname: "quaoar"
    ipAddress: "10.20.20.52"
    installDiskSelector:
      wwid: "naa.50026b738121a9bd"
    networkInterfaces:
      - <<: *networkInterface
        deviceSelector:
          hardwareAddr: "02:26:26:02:27:5a"
        dhcp: false
        addresses:
          - "10.20.20.52/24"
        vlans:
          - <<: *vlan
            addresses:
              - "10.20.50.52/24"
  - <<: *intelNode
    hostname: "hygiea"
    ipAddress: "10.20.20.53"
    installDiskSelector:
      wwid: "naa.500a0751e1d4d161"
    networkInterfaces:
      - <<: *networkInterface
        deviceSelector:
          hardwareAddr: "00:e0:4c:68:13:04"
        dhcp: false
        addresses:
          - "10.20.20.53/24"
        vlans:
          - <<: *vlan
            addresses:
              - "10.20.50.53/24"
    schematic: &intelDellSchematic
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
          - cpufreq.default_governor=performance # Default is powersave
          - iommu.passthrough=1 # Less security, faster puter
          - pci=nommconf # Apparently required: https://unix.stackexchange.com/questions/327730/what-causes-this-pcieport-00000003-0-pcie-bus-error-aer-bad-tlp#369090
        systemExtensions: *intelExtensions
  - <<: *intelNode
    hostname: "eris"
    ipAddress: "10.20.20.54"
    installDiskSelector:
      wwid: "naa.50026b738121a9cf"
    networkInterfaces:
      - <<: *networkInterface
        deviceSelector:
          hardwareAddr: "00:e0:4c:68:14:1f"
        dhcp: false
        addresses:
          - "10.20.20.54/24"
        vlans:
          - <<: *vlan
            addresses:
              - "10.20.50.54/24"
    schematic: *intelDellSchematic
#  - &rockNode
#    hostname: "haumea"
#    ipAddress: "10.20.20.55"
#    installDiskSelector:
#      wwid: "eui.002538b921b9e16a"
#    machineSpec:
#      secureboot: false
#      arch: "arm64"
#      mode: "metal"
#    kernelModules:
#      - name: vfio_pci
#      - name: uio_pci_generic
#    schematic:
#      overlay:
#        image: siderolabs/sbc-rockchip
#        name: rock5b
#      customization:
#        extraKernelArgs:
#          - -init_on_alloc # Less security, faster puter
#          - -init_on_free # Less security, faster puter
#          - -selinux # Less security, faster puter
#          - apparmor=0 # Less security, faster puter
#          - init_on_alloc=0 # Less security, faster puter
#          - init_on_free=0 # Less security, faster puter
#          - iommu=pt # PCI Passthrough
#          - mitigations=off # Less security, faster puter
#          - security=none # Less security, faster puter
#          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
#          - talos.auditd.disabled=1 # Less security, faster puter
#          - cpufreq.default_governor=performance # Default is powersave
#          - iommu.passthrough=1 # Less security, faster puter
#        systemExtensions:
#          officialExtensions:
#            - siderolabs/nfsd
#            - siderolabs/nfsrahead
#            - siderolabs/util-linux-tools
#            - siderolabs/nvme-cli
#            - siderolabs/iscsi-tools
#    controlPlane: true
#    volumes:
#      - name: EPHEMERAL
#        provisioning:
#          diskSelector:
#            match: disk.transport == 'nvme'
#          minSize: 2GB
#          maxSize: 75GB
#          grow: false
#    userVolumes:
#      - *ebsVolume
#    networkInterfaces:
#      - deviceSelector:
#          hardwareAddr: "00:e0:4c:68:00:4f"
#        dhcp: false
#        addresses:
#          - "10.20.20.55/24"
#        routes:
#          - gateway: "10.20.20.1"
#            network: 0.0.0.0/0
#        mtu: 9000
#        vip:
#          ip: "10.20.20.100"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-hugepages.yaml"
  - "@./patches/global/longhorn-partition.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

