apiVersion: v1
kind: Secret
metadata:
  name: ha-postgres
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:N6+pjA1Bg+s=,iv:RyHhDDyIUj5EELacJjE5wgqvjxSJraAonih+/8Vt4SY=,tag:TGHao9+4AC0j/Vq/Hsz7JA==,type:str]
  password: ENC[AES256_GCM,data:hh46RZc2pnjODton5hmBZVVlfWuUJt+dt6D3mIyPME4=,iv:nZCALULHxpa7cATGUhFJEkdG6fViWjKJ3VRCbI0POls=,tag:zmmenqKIHZTHaUgvfU85ww==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVk2aEp3SXQ5cXdqb3gy
        VkU1M1Z4ZW9tTUpVejB3Q1pGRVd0Wnc4NVJBCnV1enp6WkNoc0RKWnhMdWFkV0E0
        Uk9BczlHZTA2ZGdNTzh3aHhnQ1haekEKLS0tIHJ0ZVVFWlRMNGgyY3U5OFBSWUpV
        VGplNmRqdWlrUWdleEZoK0Z5N28za28KTr0RPTfKZF+TK+b65ipr2yxsrTahJjVt
        dSO+xVV34XCd9RiWMhXgENpSXO5p7lw7+3CwkrxTMrkXY1NZQdwx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T18:58:36Z"
  mac: ENC[AES256_GCM,data:IsvOF63O3I8AqV3DNaKOzkZnY2Q5CQ7hvSboISpiJwkw0HKECmW/QZj87v/e7llftJu14dCvZDNJ7IVF/3fp1UuS6aluLxjicBpskCZRjAbZM7apSpvt5IrIZ00c+IeaPNZ2zdPDxm6FeCXccI5Y9VGvg4oBaMaDxl3cllWGUMM=,iv:btZx1TK7A9mfKGPtKwCCyV/3qrxnXPCe7k3Ptd92HEQ=,tag:3+FUf+3NbaX0lBdCHzxLqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
