apiVersion: v1
kind: Secret
metadata:
  name: ha-postgres
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:MaFOSRaAH+Q0q8G/JQU=,iv:ZPqS4/AfMNhzw0vnimKGhyxjnOenA38lEYWqAwOa6bY=,tag:ususDfdGTEFgr9iOWlYivA==,type:str]
  password: ENC[AES256_GCM,data:hh46RZc2pnjODton5hmBZVVlfWuUJt+dt6D3mIyPME4=,iv:nZCALULHxpa7cATGUhFJEkdG6fViWjKJ3VRCbI0POls=,tag:zmmenqKIHZTHaUgvfU85ww==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVk2aEp3SXQ5cXdqb3gy
        VkU1M1Z4ZW9tTUpVejB3Q1pGRVd0Wnc4NVJBCnV1enp6WkNoc0RKWnhMdWFkV0E0
        Uk9BczlHZTA2ZGdNTzh3aHhnQ1haekEKLS0tIHJ0ZVVFWlRMNGgyY3U5OFBSWUpV
        VGplNmRqdWlrUWdleEZoK0Z5N28za28KTr0RPTfKZF+TK+b65ipr2yxsrTahJjVt
        dSO+xVV34XCd9RiWMhXgENpSXO5p7lw7+3CwkrxTMrkXY1NZQdwx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:28:02Z"
  mac: ENC[AES256_GCM,data:PltYnhbtrSyh3jsIKlBXZVGNJoUnWC7JdFAv/dMk4Ed5VmlJPVd9mCOTSIfgXhN22STtKRlipU/UqR8W7GXC+xKr8RFy+bElqeWwg7EIPEBzMzgK5/u6hMrMeOqqRmwguQ9I3mjYCxFsXRfCIG3XfCXLMM60HlY1oScjXRaubJQ=,iv:/gR4u/f9awoXrYeIyLJkVKIm8Usvkg57J7Za2+sje88=,tag:KLSfdrYzlE26m34IsCnq7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
