apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:nHxPvnwMz3fHmrQaPmlNLEOcJRxc,iv:nmfmPIe2T44g18NLw5igTvqAvX5RR03P8arN+b1WPJc=,tag:pjdaQ6jdv5KRXFuAuXMtDA==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:KDin7mUacWEmCodwjMN3TuU/R9k=,iv:s70QXz9dclZwutNvM2be96gp+B2jkywolfs34RrT5Cs=,tag:1GQg6QfXZBlGUThl7BVfwQ==,type:str]
sops:
  age:
    - recipient: age18j2m4d43ks065lkuy40ge26xd86sss3289p0ntjklfmdns4pugxslq9jx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVk2aEp3SXQ5cXdqb3gy
        VkU1M1Z4ZW9tTUpVejB3Q1pGRVd0Wnc4NVJBCnV1enp6WkNoc0RKWnhMdWFkV0E0
        Uk9BczlHZTA2ZGdNTzh3aHhnQ1haekEKLS0tIHJ0ZVVFWlRMNGgyY3U5OFBSWUpV
        VGplNmRqdWlrUWdleEZoK0Z5N28za28KTr0RPTfKZF+TK+b65ipr2yxsrTahJjVt
        dSO+xVV34XCd9RiWMhXgENpSXO5p7lw7+3CwkrxTMrkXY1NZQdwx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T21:28:47Z"
  mac: ENC[AES256_GCM,data:Eorl0Av1XuE4jj8lr1wyTbQ6PEjBqzw38ynfaPLWRxU1zM6ZVuudBOBsL6QdD21aUTlWb6oRM1dzeqiEpVmHoGHTuwQuXCdtVEq7IO9UUiP8jUlf7eLgtifc/H/+Tuv1bT25aM0480QWJsUzMkEudn1vAS/I44G5J2KJpTGD8us=,iv:AAPfyFnInjjdEypI/J7iLyDiOhsDlmb7bqyAAr0tSBc=,tag:HS3AWKS9gRTaQ5w3QEkpAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
